jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out Git repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      id: maven-build
      name: Build with Maven
      run: mvn --batch-mode --update-snapshots -Dgpg.skip=true clean verify
    - continue-on-error: true
      if: failure() && steps.maven-build.outcome == 'failure'
      name: Upload decompilation test failures artifact
      uses: actions/upload-artifact@v2
      with:
        name: decompilation-test-failures-diff
        path: target/cfr-test-failures-diff
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
